<?php

namespace Database\Factories;

use App\Models\Fournisseur;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class ConsignmentReceptionFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\Illuminate\Database\Eloquent\Model>
     */
    protected $model = \App\Models\Purchasing\ConsignmentReception::class;

    /**
     * Get the name of the model that is generated by the factory.
     */
    public function modelName(): string
    {
        return \App\Models\Purchasing\ConsignmentReception::class;
    }

    public function definition(): array
    {
        return [
            'fournisseur_id' => Fournisseur::factory(),
            'reception_date' => $this->faker->dateTimeBetween('-30 days', 'now'),
            'unit_of_measure' => $this->faker->randomElement(['unit', 'box', 'pack']),
            'origin_note' => $this->faker->optional()->sentence(),
            'reception_type' => 'consignment',
            'operation_type' => 'manual',
            'created_by' => User::factory(),
        ];
    }
}
