<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Audit Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: Arial, sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #333;
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 3px solid #2563eb;
        }
        
        .header h1 {
            color: #1e40af;
            font-size: 24px;
            margin-bottom: 10px;
        }
        
        .header .subtitle {
            color: #6b7280;
            font-size: 12px;
        }
        
        .info-section {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }
        
        .info-box {
            padding: 10px;
            background: #f3f4f6;
            border-radius: 5px;
        }
        
        .info-box strong {
            color: #1f2937;
        }
        
        .summary {
            margin-bottom: 30px;
            padding: 15px;
            background: linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%);
            border-radius: 8px;
            border-left: 4px solid #2563eb;
        }
        
        .summary h2 {
            color: #1e40af;
            font-size: 16px;
            margin-bottom: 15px;
        }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 15px;
        }
        
        .summary-item {
            background: white;
            padding: 12px;
            border-radius: 6px;
            text-align: center;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        
        .summary-item .label {
            color: #6b7280;
            font-size: 10px;
            margin-bottom: 5px;
        }
        
        .summary-item .value {
            font-size: 20px;
            font-weight: bold;
        }
        
        .summary-item.total .value {
            color: #2563eb;
        }
        
        .summary-item.differences .value {
            color: #f59e0b;
        }
        
        .summary-item.shortage .value {
            color: #ef4444;
        }
        
        .summary-item.overage .value {
            color: #10b981;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        thead {
            background: #1e40af;
            color: white;
        }
        
        th {
            padding: 10px 8px;
            text-align: left;
            font-weight: bold;
            font-size: 10px;
            border: 1px solid #1e3a8a;
        }
        
        td {
            padding: 8px;
            border: 1px solid #e5e7eb;
            font-size: 10px;
        }
        
        tbody tr:nth-child(even) {
            background: #f9fafb;
        }
        
        tbody tr:hover {
            background: #f3f4f6;
        }
        
        .positive {
            color: #10b981;
            font-weight: bold;
        }
        
        .negative {
            color: #ef4444;
            font-weight: bold;
        }
        
        .zero {
            color: #6b7280;
        }
        
        .variance-low {
            color: #fbbf24;
        }
        
        .variance-medium {
            color: #f97316;
        }
        
        .variance-high {
            color: #dc2626;
            font-weight: bold;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 2px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 10px;
        }
        
        .page-break {
            page-break-after: always;
        }
        
        @media print {
            body {
                padding: 10px;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 Inventory Audit Report</h1>
        <p class="subtitle">Physical Stock Count vs Theoretical Quantities</p>
    </div>
    
    <div class="info-section">
        <div class="info-box">
            <strong>Generated:</strong> {{ $generated_at }}
        </div>
        <div class="info-box">
            <strong>Generated By:</strong> {{ $generated_by }}
        </div>
    </div>
    
    <div class="summary">
        <h2>📊 Audit Summary</h2>
        <div class="summary-grid">
            <div class="summary-item total">
                <div class="label">Total Items Audited</div>
                <div class="value">{{ $summary['total_items'] }}</div>
            </div>
            <div class="summary-item differences">
                <div class="label">Items with Differences</div>
                <div class="value">{{ $summary['items_with_differences'] }}</div>
            </div>
            <div class="summary-item shortage">
                <div class="label">Total Shortage</div>
                <div class="value">{{ number_format($summary['total_shortage'], 2) }}</div>
            </div>
            <div class="summary-item overage">
                <div class="label">Total Overage</div>
                <div class="value">{{ number_format($summary['total_overage'], 2) }}</div>
            </div>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th style="width: 5%">#</th>
                <th style="width: 25%">Product Name</th>
                <th style="width: 15%">Stockage</th>
                <th style="width: 12%">Theoretical Qty</th>
                <th style="width: 12%">Actual Qty</th>
                <th style="width: 10%">Difference</th>
                <th style="width: 8%">Variance %</th>
                <th style="width: 13%">Notes</th>
            </tr>
        </thead>
        <tbody>
            @foreach($audit_items as $index => $item)
            <tr>
                <td style="text-align: center;">{{ $index + 1 }}</td>
                <td><strong>{{ $item['product_name'] }}</strong></td>
                <td>{{ $item['stockage_name'] }}</td>
                <td style="text-align: right;">{{ number_format($item['theoretical_quantity'], 2) }}</td>
                <td style="text-align: right;">{{ number_format($item['actual_quantity'], 2) }}</td>
                <td style="text-align: right;" class="@if($item['difference'] > 0) positive @elseif($item['difference'] < 0) negative @else zero @endif">
                    {{ $item['difference'] > 0 ? '+' : '' }}{{ number_format($item['difference'], 2) }}
                </td>
                <td style="text-align: right;" 
                    class="@if(abs($item['variance_percent']) < 5) @elseif(abs($item['variance_percent']) < 10) variance-low @elseif(abs($item['variance_percent']) < 20) variance-medium @else variance-high @endif">
                    {{ number_format($item['variance_percent'], 1) }}%
                </td>
                <td style="font-size: 9px;">{{ $item['notes'] ?? '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p><strong>Hospital Information System</strong> - Inventory Management Module</p>
        <p>This is a computer-generated document. Discrepancies should be investigated and approved by management.</p>
    </div>
</body>
</html>
