<?php

return [
    'father' => 'Son Père → His/Her father',
    'grandfather' => 'Son Grand Père → His/Her grandfather',
    'mother' => 'Sa Mère → His/Her mother',
    'grandmother' => 'Sa Grand-Mère → His/Her grandmother',
    'husband' => 'Son Epoux → His/Her husband',
    'wife' => 'Son Epouse → His/Her wife',
    'son' => 'Son Fils → His/Her son',
    'grandson' => 'Son Petit Fils → His/Her grandson',
    'stepson' => 'Son Beau Fils → His/Her stepson / son-in-law',
    'daughter' => 'Sa Fille → His/Her daughter',
    'granddaughter' => 'Sa Petite Fille → His/Her granddaughter',
    'stepdaughter' => 'Sa Belle Fille → His/Her stepdaughter / daughter-in-law',
    'brother' => 'Son Frère → His/Her brother',
    'brother_maternal' => 'Son Frère Mat. → His/Her maternal half-brother',
    'brother_paternal' => 'Son Frère Pat. → His/Her paternal half-brother',
    'sister' => 'Sa Sœur → His/Her sister',
    'sister_maternal' => 'Sa Sœur Mat. → His/Her maternal half-sister',
    'sister_paternal' => 'Sa Sœur Pat. → His/Her paternal half-sister',
    'cousin_male' => 'Son Cousin → His/Her male cousin',
    'cousin_female' => 'Son Cousine → His/Her female cousin',
    'cousin_maternal_male' => 'Son Cousin Mat. → His/Her maternal cousin (male)',
    'cousin_maternal_female' => 'Son Cousine Mat. → His/Her maternal cousin (female)',
    'uncle' => 'Son Oncle → His/Her uncle',
    'uncle_maternal' => 'Son Oncle Mat. → His/Her maternal uncle',
    'aunt' => 'Sa Tante → His/Her aunt',
    'aunt_maternal' => 'Sa Tante Mat. → His/Her maternal aunt',
    'nephew' => 'Son Neveu → His/Her nephew',
    'niece' => 'Sa Nièce → His/Her niece',
    'close_family' => 'Sa Famille (Proche) → His/Her close family',
    'son_in_law' => 'Son Gendre → His/Her son-in-law',
    'friend' => 'Son Ami → His/Her friend',
    'colleague' => 'Son Collègue → His/Her colleague',
    'physician' => 'Son Médecin → His/Her physician',
    'assistant' => 'Son Assistant → His/Her assistant',
    'nurse' => 'Son Infirmier → His/Her nurse',
    'paramedic' => 'Son Ambulancier → His/Her paramedic / ambulance worker',
    'dependant' => 'Son Charge → His/Her dependant / charge',
    'benefactor' => 'Son Bienfaiteur → His/Her benefactor',
    'escort' => 'Son Accompagnateur → His/Her escort / accompanying person',
    'mother_in_law' => 'Belle-Mère → Mother-in-law / stepmother',
    'father_in_law' => 'Beau-Père → Father-in-law / stepfather',
];
