INSERT INTO doctors (
    id,
    specialization_id,
    number_of_patient,
    frequency,
    specific_date,
    notes,
    patients_based_on_time,
    time_slot,
    appointment_booking_window,
    created_by,
    user_id,
    deleted_at,
    created_at,
    updated_at,
    schedule_id
  )
VALUES (
    'id:bigint',
    'specialization_id:bigint',
    number_of_patient:int,
    'frequency:enum',
    'specific_date:date',
    'notes:text',
    'patients_based_on_time:tinyint',
    time_slot:int,
    appointment_booking_window:int,
    created_by:int,
    'user_id:bigint',
    'deleted_at:timestamp',
    'created_at:timestamp',
    'updated_at:timestamp',
    'schedule_id:bigint'
  );